import type { Readable } from "node:stream";

export type ObjectStat = { size: number; contentType?: string };

export type ByteRange = { start: number; end: number };

/**
 * Durable object storage. Keys look like
 *   projects/{project_id}/{characters|scenes|shots|audio|subtitles|final}/...
 * and are always generated by the server (never taken from user input).
 */
export interface StorageProvider {
  readonly driver: "local" | "s3";
  put(key: string, data: Buffer, contentType: string): Promise<void>;
  putFile(key: string, filePath: string, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer>;
  getStream(key: string, range?: ByteRange): Promise<Readable>;
  stat(key: string): Promise<ObjectStat | null>;
  delete(key: string): Promise<void>;
  downloadToFile(key: string, filePath: string): Promise<void>;
  /** Signed URL for direct download, or null if the driver serves via the app. */
  signedUrl(key: string, opts: { ttlSec: number; downloadName?: string }): Promise<string | null>;
}

const KEY_RE = /^projects\/[0-9a-f-]{36}\/(characters|locations|scenes|shots|audio|subtitles|final|work)\/[A-Za-z0-9._\-/]+$/;

export function assertValidKey(key: string): void {
  if (!KEY_RE.test(key) || key.includes("..") || key.includes("//")) {
    throw new Error(`Invalid storage key: ${key}`);
  }
}

export type StorageFolder = "characters" | "locations" | "scenes" | "shots" | "audio" | "subtitles" | "final";

export function storageKey(projectId: string, folder: StorageFolder, name: string): string {
  const safeName = name.replace(/[^A-Za-z0-9._-]/g, "_").replace(/\.{2,}/g, "_");
  const key = `projects/${projectId}/${folder}/${safeName}`;
  assertValidKey(key);
  return key;
}
